---
title: Piymis.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title_left: Piyush
title_right: Mishra
description: Blog
keywords: Programming
url: https://piymis.github.io
baseurl: ''
cover: ''
google_analytics: UA-96336242-1
twitter_username: piy_mis
comments_enabled: true
disqus_shortname: piymis-github-io
postshare_enabled: false
permalink: "/:year/:title/"
markdown: kramdown
highlighter: rouge
source: "./"
destination: "./_site"
sass:
  sass_dir: assets/scss
  style: compressed
author:
  name: Piyush Mishra
plugins:
- jekyll-sitemap
- bourbon
- jekyll-paginate
navbar:
- slug: about
  title: About
- slug: blog
  title: Blog
exclude:
- gulp
- node_modules
- bower
- bower_components
- config.rb
- src
- Gemfile
- Gemfile.lock
- ".rvmrc"
- ".rbenv-version"
- package.json
- gulpfile.js
- README.md
- Rakefile
- changelog.md
- script
- vendor
