
# SEO settings
title: "Piyush Mishra"
title2: ""# default: ""
description: "Blog"
keywords: "programming,"
url: http://piymis.github.io # site url
#baseurl: "" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-96336242-1 
repo: https://github.com/piymis/piymis.github.io
disqus_shortname: "piymis-github-io"
twitter_username: "piy_mis"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Piyush Mishra"
  job      : "Programmer"
  bio      : ""
  thumb    : /images/author.jpg
  email    : hnrird@gmail.com
  url      : http://piymis.github.io
  github   : http://github.com/piymis
  twitter  : http://twitter.com/piy_mis
  facebook : 
  linkedin : http://linkedin.com/in/piymis

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@piy_mis"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
